### ISSUE TITLE
Add config option to not delete existing routes

### ISSUE THREAD

**Issue by dschmidtadv** [detroitenglish/cloudflare-worker-webpack-boilerplate#2]
There should be a config option to not delete existing routes, and it should be enabled by default to avoid accidentally deleting routes.

**Comment by detroitenglish** [comment]
This boilerplate is intended to be a starting point for using CF workers, **not** a full-featured management utility.

Clearing all existing routes on every deployment ensures that the boilerplate config and Cloudflare are in sync. If they aren't, intended users (i.e. beginners) will experienced unexpected behavior due to leftover route patterns, and need to manually delete routes through the API or CF Dashboard. 

That goes against the design goals of this project, and the intended behavior is very clearly documented in the provided [example.env](https://github.com/detroitenglish/cloudflare-worker-webpack-boilerplate/blob/2e92b8be2168aec9209b989f3b5749e10504270c/example.env#L35).
